Dynamic methods
DiamondLightSource/FastCS pull request #87
Opened 2024-11-20 13:23 UTC by GDYendell

Fixes #74

2025-01-23 11:38 UTC, GDYendell commented
Update 'Command' and 'BoundCommand' to 'UnboundCommand` and `Command`.

2025-03-05 09:20 UTC, evalott100 requested changes
I really like abstracting this stuff out of controller, nice job!

2025-03-05 15:41 UTC, GDYendell commented on src/fastcs/controller_api.py
> +class ControllerAPI:
I guess I was thinking of it is as a API of the `Controller` that is exposed to the transport layer, rather than the API for writing drivers. I am open to other names, but I was keen to get rid of "mapping"!

2025-03-05 16:03 UTC, GDYendell commented on src/fastcs/launch.py
> +                        self._backend.controller_api,
When you say downstream do you mean when writing controllers? I think that is right... The transports do need to be public because some drivers may want to implement their own `__main__.py` that imports and instantiates them manually. Although, maybe we want to get rid of that as an option in future.

What would you change here?

2025-03-05 16:12 UTC, GDYendell commented on src/fastcs/cs_methods.py
> +        if not len(self.parameters) == 0:
In `UnboundScan`, `fn` is `function MyTestController.counter`, which takes `self` as an
argument. in `Scan`, `fn` is `bound method MyTestController.counter of <tests.conftest.BackendTestController object at 0x7fbc9e626110`, which takes no arguments.

I will add some explanation.

2025-03-05 16:30 UTC, GDYendell commented on src/fastcs/controller_api.py
> +    return _build_controller_api(controller, [])
This is nicer, but I am now thinking that these functions should live in backend.py, as that is the thing that knows about both `Controller` and `ControllerAPI` - I don't think they need to know about each other directly at all. What do you think?

2025-03-06 08:48 UTC, evalott100 commented on src/fastcs/controller_api.py
> +    return _build_controller_api(controller, [])
That sounds good!

2025-03-06 08:58 UTC, evalott100 commented on src/fastcs/launch.py
> +                        self._backend.controller_api,
> What would you change here?

I think my main concern is that `ControllerAPI` is a big dataclass of everything the FastCS side will parse out of controllers, it should be private since it's FastCS implementation detail that shouldn't need to be considered when writing controllers. At the same time if a user wants to run a transport directly through `EpicsTransport`, they would have to pass `build_controller_api(controller)` instead of `controller`.

I think it would be better if we passed in a single `Backend` to these transport and removed the `loop` argument (which is contained in `Backend`).

If we do

https://github.com/DiamondLightSource/FastCS/pull/87#discussion_r1981771169

then the user doesn't have to worry about what the `ControllerAPI` is.

2025-03-06 13:20 UTC, GDYendell commented on src/fastcs/launch.py
> +                        self._backend.controller_api,
Yep I agree with this. It is becoming a bit unclear to me where the public interface should be drawn, but I think making the backend public rather than the controller api is nicer.

2025-03-06 13:35 UTC, evalott100 commented on src/fastcs/controller_api.py
> +class ControllerAPI:
> I am open to other names

Now it'll be private and we probably don't need to bother!

2025-03-06 13:49 UTC, GDYendell commented on src/fastcs/launch.py
> +                        self._backend.controller_api,
Actually, I don't like this because if the transport has the backend then it has the controller and it shouldn't. So I think until we make the transports private and reduce the public api for writing controllers to just the FastCS class, ControllerAPI should be public too...

2025-03-06 14:49 UTC, evalott100 commented on src/fastcs/launch.py
> +                        self._backend.controller_api,
I'm happy with that so long as we choose an option now. Why would `ControllerAPI` need to be public if transports aren't? What would it be used for?

2025-03-10 08:44 UTC, evalott100 approved these changes

2025-03-10 08:44 UTC, evalott100 commented on src/fastcs/controller_api.py
> +    return _build_controller_api(controller, [])
We could still change the method to `from_controller(cls, ...)`, up to you.

2025-03-10 08:44 UTC, evalott100 commented on src/fastcs/backend.py
> +def build_controller_api(controller: Controller) -> ControllerAPI:
Still think it would be nice for this should be a static `ControllerAPI` method, but up to you.

2025-03-10 10:00 UTC, GDYendell commented on src/fastcs/backend.py
> +def build_controller_api(controller: Controller) -> ControllerAPI:
I think I prefer it like this just because it means `Controller` and `ControllerAPI` have no knowledge of each other.

2025-03-10 10:00 UTC, merged